// Generated by Isabelle-LLVM. Do not modify.
#ifndef _INTROSORTXXX_H
#define _INTROSORTXXX_H 1


typedef struct {
  int64_t size;
  struct {
    int64_t capacity;
    char*data;
  };
} llstring;

char llstrcmp(llstring*, llstring*);
void str_init(llstring*);
void str_append(llstring*, char);
llstring* str_introsort(llstring*, int64_t, int64_t);
uint64_t* heapsort(uint64_t*, int64_t, int64_t);
uint64_t* introsort(uint64_t*, int64_t, int64_t);
uint64_t* insertion_sort(uint64_t*, int64_t, int64_t);
uint64_t* introsort_aux(uint64_t*, int64_t, int64_t, int64_t);

#endif
