; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%LLVM_Examples_my_pair = type { i64, i32 }

declare i8* @isabelle_llvm_calloc(i64, i64)


define i64 @LLVM_Examples_add_add(i64 %a) {

  start:
    %x = add i64 %a, %a
    %x1 = add i64 %x, %x
    ret i64 %x1
}

define i32 @LLVM_Examples_add_add1(i32 %a) {

  start:
    %x = add i32 %a, %a
    %x1 = add i32 %x, %x
    ret i32 %x1
}

define i32 @LLVM_Examples_test_named(i32 %a, i64 %b) {

  start:
    %a1 = call i32 @LLVM_Examples_add_add1 (i32 %a)
    %b1 = call i64 @LLVM_Examples_add_add (i64 %b)
    %aa = extractvalue %LLVM_Examples_my_pair zeroinitializer, 0
    %ba = extractvalue %LLVM_Examples_my_pair zeroinitializer, 1
    %n = insertvalue %LLVM_Examples_my_pair zeroinitializer, i64 zeroinitializer, 0
    %na = insertvalue %LLVM_Examples_my_pair %n, i32 zeroinitializer, 1
    %t = getelementptr %LLVM_Examples_my_pair, %LLVM_Examples_my_pair* null, i64 1
    %c = ptrtoint %LLVM_Examples_my_pair* %t to i64
    %d = call i8* @isabelle_llvm_calloc (i64 1, i64 %c)
    %p = bitcast i8* %d to %LLVM_Examples_my_pair*
    %p1 = getelementptr %LLVM_Examples_my_pair, %LLVM_Examples_my_pair* %p, i32 0, i32 0
    %p2 = getelementptr %LLVM_Examples_my_pair, %LLVM_Examples_my_pair* %p, i32 0, i32 1
    ret i32 %ba
}
