; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"






define i64 @exp64(i64 %r) {

  start:
    %xa = insertvalue { i64, i64 } zeroinitializer, i64 1, 0
    %xaa = insertvalue { i64, i64 } %xa, i64 %r, 1
    br label %while_start

  while_start:
    %xba = phi { i64, i64 } [ %x2, %while_body ], [ %xaa, %start ]
    %a = extractvalue { i64, i64 } %xba, 0
    %x = extractvalue { i64, i64 } %xba, 1
    %x1 = icmp ult i64 0, %x
    br i1 %x1, label %while_body, label %while_end

  while_body:
    %a1 = extractvalue { i64, i64 } %xba, 0
    %r1 = extractvalue { i64, i64 } %xba, 1
    %tmpaaa = mul i64 %a1, 2
    %xaaa = insertvalue { i64, i64 } zeroinitializer, i64 %tmpaaa, 0
    %tmpb = sub i64 %r1, 1
    %x2 = insertvalue { i64, i64 } %xaaa, i64 %tmpb, 1
    br label %while_start

  while_end:
    %a2 = extractvalue { i64, i64 } %xba, 0
    %r2 = extractvalue { i64, i64 } %xba, 1
    ret i64 %a2
}

define i32 @exp32(i32 %r) {

  start:
    %xa = insertvalue { i32, i32 } zeroinitializer, i32 1, 0
    %xaa = insertvalue { i32, i32 } %xa, i32 %r, 1
    br label %while_start

  while_start:
    %xba = phi { i32, i32 } [ %x2, %while_body ], [ %xaa, %start ]
    %a = extractvalue { i32, i32 } %xba, 0
    %x = extractvalue { i32, i32 } %xba, 1
    %x1 = icmp ult i32 0, %x
    br i1 %x1, label %while_body, label %while_end

  while_body:
    %a1 = extractvalue { i32, i32 } %xba, 0
    %r1 = extractvalue { i32, i32 } %xba, 1
    %tmpaaa = mul i32 %a1, 2
    %xaaa = insertvalue { i32, i32 } zeroinitializer, i32 %tmpaaa, 0
    %tmpb = sub i32 %r1, 1
    %x2 = insertvalue { i32, i32 } %xaaa, i32 %tmpb, 1
    br label %while_start

  while_end:
    %a2 = extractvalue { i32, i32 } %xba, 0
    %r2 = extractvalue { i32, i32 } %xba, 1
    ret i32 %a2
}
