// Generated by Isabelle-LLVM. Do not modify.
#ifndef _INTROSORT_PARAM_H
#define _INTROSORT_PARAM_H 1




uint64_t* heapsort_idxs(uint32_t*, uint64_t*, int64_t, int64_t);
uint64_t* introsort_idxs(uint32_t*, uint64_t*, int64_t, int64_t);

#endif
