// Generated by Isabelle-LLVM. Do not modify.
#ifndef _INTROSORT_H
#define _INTROSORT_H 1




uint64_t* heapsort(uint64_t*, int64_t, int64_t);
uint64_t* introsort(uint64_t*, int64_t, int64_t);
uint64_t* insertion_sort(uint64_t*, int64_t, int64_t);
uint64_t* introsort_aux(uint64_t*, int64_t, int64_t, int64_t);

#endif
