; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%list_cell_i1 = type { i1, %list_cell_i1* }




define %list_cell_i1 @LLVM_Examples_llist_append(i1 %x, %list_cell_i1* %l) {

  start:
    %r = insertvalue %list_cell_i1 zeroinitializer, i1 %x, 0
    %x1 = insertvalue %list_cell_i1 %r, %list_cell_i1* %l, 1
    ret %list_cell_i1 %x1
}
