; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%my_pair_i32_i64 = type { i32, i64 }



attributes #0 = { strictfp }

define i64 @LLVM_Examples_add_add(i64 %a) #0 {

  start:
    %x = add i64 %a, %a
    %x1 = add i64 %x, %x
    ret i64 %x1
}

define i32 @LLVM_Examples_add_add1(i32 %a) #0 {

  start:
    %x = add i32 %a, %a
    %x1 = add i32 %x, %x
    ret i32 %x1
}

define i64 @LLVM_Examples_test_named(i32 %a, i64 %b) #0 {

  start:
    %a1 = call i32 @LLVM_Examples_add_add1 (i32 %a)
    %b1 = call i64 @LLVM_Examples_add_add (i64 %b)
    %aa = extractvalue %my_pair_i32_i64 zeroinitializer, 0
    %ba = extractvalue %my_pair_i32_i64 zeroinitializer, 1
    %n = insertvalue %my_pair_i32_i64 zeroinitializer, i32 zeroinitializer, 0
    %na = insertvalue %my_pair_i32_i64 %n, i64 zeroinitializer, 1
    ret i64 %ba
}
