// Generated by Isabelle-LLVM. Do not modify.
#ifndef _TEST_NAMED_H
#define _TEST_NAMED_H 1


#include <stdint.h>


typedef struct my_pair_i64_i64 my_pair_i64_i64;

typedef struct my_pair_i64_i64 {
  int64_t field0;
  int64_t field1;
} my_pair_i64_i64;

int64_t test_named(int32_t, int64_t);
int64_t my_pair_sum(my_pair_i64_i64*);

#endif
