; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"




define void @arraycpy(i8* %dst, i8* %src, i64 %n) {

  start:
    %uu = call i64 @LLVM_Shallow_RS_arraycpy_0 (i8* %dst, i8* %src, i64 %n, i64 0)
    ret void
}

define i64 @LLVM_Shallow_RS_arraycpy_0(i8* %dst, i8* %src, i64 %n, i64 %s) {

  start:
    %ctd = icmp ult i64 %s, %n
    br i1 %ctd, label %then, label %else

  then:
    %x = getelementptr i8, i8* %src, i64 %s
    %x1 = load i8, i8* %x
    %p = getelementptr i8, i8* %dst, i64 %s
    store i8 %x1, i8* %p
    %x2 = add i64 %s, 1
    %x3 = call i64 @LLVM_Shallow_RS_arraycpy_0 (i8* %dst, i8* %src, i64 %n, i64 %x2)
    br label %ctd_if

  else:
    br label %ctd_if

  ctd_if:
    %xa = phi i64 [ %x3, %then ], [ %s, %else ]
    ret i64 %xa
}
