; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

declare  i8* @isabelle_llvm_calloc(i64, i64)


define i32 @main(i32 %argc, i8** %argv) {

  start:
    %r = call i16 @LLVM_Shallow_test2 (i32 %argc)
    %x = zext i16 %r to i32
    ret i32 %x
}

define i16 @LLVM_Shallow_test2(i32 %n) {

  start:
    %n1 = add i32 %n, 42
    %a = zext i32 %n1 to i64
    %t = getelementptr i16, i16* null, i64 1
    %b = ptrtoint i16* %t to i64
    %p = call i8* @isabelle_llvm_calloc (i64 %a, i64 %b)
    %pa = bitcast i8* %p to i16*
    %paa = getelementptr i16, i16* %pa, i32 5
    store i16 42, i16* %paa
    %x = load i16, i16* %paa
    ret i16 %x
}
