; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

declare  void @isabelle_llvm_free(i8*)
declare  i8* @isabelle_llvm_calloc(i64, i64)


define i32 @main(i32 %argc, i8** %argv) {

  start:
    %a = zext i32 30 to i64
    %t = getelementptr i32, i32* null, i64 1
    %b = ptrtoint i32* %t to i64
    %p = call i8* @isabelle_llvm_calloc (i64 %a, i64 %b)
    %pa = bitcast i8* %p to i32*
    %p1 = getelementptr i32, i32* %pa, i32 5
    %x = load i32, i32* %p1
    %x1 = add i32 %x, 10
    %x2 = udiv i32 %x1, 4
    %x3 = add i32 %x2, %argc
    store i32 %x3, i32* %p1
    %x4 = load i32, i32* %p1
    %p2 = getelementptr i32, i32* %p1, i32 -5
    %c = bitcast i32* %p2 to i8*
    call void @isabelle_llvm_free (i8* %c)
    ret i32 %x4
}
