// Generated by Isabelle-LLVM. Do not modify.
#ifndef __BIN_SEARCH_H_H
#define __BIN_SEARCH_H_H 1


typedef uint64_t elem_t;
typedef struct{
  int64_t len;
  elem_t*data;
}larray_t;

int64_t bin_search(larray_t,elem_t);

#endif
