; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"






define i32 @euclid(i32 %a, i32 %b) {

  start:
    %x = insertvalue { i32, i32 } zeroinitializer, i32 %a, 0
    %xa = insertvalue { i32, i32 } %x, i32 %b, 1
    %xb = call { i32, i32 } @LLVM_Examples_euclid2_0 ({ i32, i32 } %xa)
    %a1 = extractvalue { i32, i32 } %xb, 0
    %b1 = extractvalue { i32, i32 } %xb, 1
    ret i32 %a1
}

define { i32, i32 } @LLVM_Examples_euclid2_0({ i32, i32 } %s) {

  start:
    %a = extractvalue { i32, i32 } %s, 0
    %x = extractvalue { i32, i32 } %s, 1
    %ctd = icmp ne i32 %a, %x
    br i1 %ctd, label %then, label %else

  then:
    %aa = extractvalue { i32, i32 } %s, 0
    %b = extractvalue { i32, i32 } %s, 1
    %tmp = icmp ule i32 %aa, %b
    br i1 %tmp, label %thena, label %elsea

  thena:
    %xa = insertvalue { i32, i32 } zeroinitializer, i32 %aa, 0
    %x1 = sub i32 %b, %aa
    %x2 = insertvalue { i32, i32 } %xa, i32 %x1, 1
    br label %ctd_ifa

  elsea:
    %x1a = sub i32 %aa, %b
    %xaa = insertvalue { i32, i32 } zeroinitializer, i32 %x1a, 0
    %x2a = insertvalue { i32, i32 } %xaa, i32 %b, 1
    br label %ctd_ifa

  ctd_ifa:
    %x1b = phi { i32, i32 } [ %x2, %thena ], [ %x2a, %elsea ]
    %x2b = call { i32, i32 } @LLVM_Examples_euclid2_0 ({ i32, i32 } %x1b)
    br label %ctd_if

  else:
    br label %ctd_if

  ctd_if:
    %x1c = phi { i32, i32 } [ %x2b, %ctd_ifa ], [ %s, %else ]
    ret { i32, i32 } %x1c
}
