// Generated by Isabelle-LLVM. Do not modify.
#ifndef _SORTING_H
#define _SORTING_H 1


typedef struct llstring llstring;

typedef struct llstring {
  int64_t size;
  struct {
    int64_t capacity;
    char*data;
  };
} llstring;

char llstrcmp(llstring*, llstring*);
void str_free(llstring*);
void str_init(llstring*);
void str_append(llstring*, char);
llstring* str_pdqsort(llstring*, int64_t, int64_t);
llstring* str_par_sort(llstring*, int64_t);
uint64_t* pdqsort(uint64_t*, int64_t, int64_t);
llstring* str_introsort(llstring*, int64_t, int64_t);
uint64_t* par_sort(uint64_t*, int64_t);
uint64_t* introsort(uint64_t*, int64_t, int64_t);

#endif
