; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"



declare float @llvm.sqrt.f32(float)


define float @test_single(float %a, float %b) {

  start:
    %aa = fmul float %a, %a
    %bb = fmul float %b, %b
    %t_1 = fadd float %aa, %bb
    %t_11 = call float @llvm.sqrt.f32 (float %t_1)
    %t_2 = fdiv float %a, %b
    %t_12 = fsub float %t_11, %t_2
    %x = fadd float %a, %b
    %x1 = frem float %t_12, %x
    ret float %x1
}
