// Generated by Isabelle-LLVM. Do not modify.
#ifndef _TEST_AVX512F_H
#define _TEST_AVX512F_H 1


#include <stdint.h>






double test_avx512f_sd_to_ninf(double, double);
double test_avx512f_sd_to_pinf(double, double);
double test_avx512f_sd_to_zero(double, double);
float test_avx512f_ss_to_ninf(float, float);
float test_avx512f_ss_to_pinf(float, float);
float test_avx512f_ss_to_zero(float, float);
double test_avx512f_sd_to_nearest(double, double);
float test_avx512f_ss_to_nearest(float, float);

#endif
