; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-p:64:64:64-a:0:64-n8:16:32:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f16:16:16-f32:32:32-f64:64:64-f128:128:128"
target triple = "x86_64-pc-linux-gnu"



declare double @llvm.sqrt.f64(double)

attributes #0 = { strictfp }

define double @test_double(double %a, double %b) #0 {

  start:
    %aa = fmul double %a, %a
    %bb = fmul double %b, %b
    %t_1 = fadd double %aa, %bb
    %t_11 = call double @llvm.sqrt.f64 (double %t_1)
    %t_2 = fdiv double %a, %b
    %t_12 = fsub double %t_11, %t_2
    %t_21 = fadd double %a, %b
    %t_13 = frem double %t_12, %t_21
    %x = fadd double %t_13, 0x3FE0000000000000
    ret double %x
}
