// Generated by Isabelle-LLVM. Do not modify.
#ifndef _TEST_AVX512F_OPS_H
#define _TEST_AVX512F_OPS_H 1


#include <stdint.h>






float avx512_32_add(int64_t, float, float);
float avx512_32_div(int64_t, float, float);
float avx512_32_mul(int64_t, float, float);
float avx512_32_sub(int64_t, float, float);
double avx512_64_add(int64_t, double, double);
double avx512_64_div(int64_t, double, double);
double avx512_64_mul(int64_t, double, double);
double avx512_64_sub(int64_t, double, double);
float avx512_32_sqrt(int64_t, float);
double avx512_64_sqrt(int64_t, double);
float avx512_32_fmadd(int64_t, float, float, float);
double avx512_64_fmadd(int64_t, double, double, double);

#endif
