// Generated by Isabelle-LLVM. Do not modify.
#ifndef _TEST_AVX512F_H
#define _TEST_AVX512F_H 1






double test_avx512f_to_ninf(double, double);
double test_avx512f_to_pinf(double, double);
double test_avx512f_to_zero(double, double);
double test_avx512f_to_nearest(double, double);

#endif
