; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-p:64:64:64-a:0:64-n8:16:32:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f16:16:16-f32:32:32-f64:64:64-f128:128:128"
target triple = "x86_64-pc-linux-gnu"



declare i64 @external_fun(i64)

attributes #0 = { strictfp }

define i64 @uses_external_fun(i64 %x) #0 {

  start:
    %x1 = call i64 @external_fun (i64 %x)
    %x2 = call i64 @external_fun (i64 %x1)
    ret i64 %x2
}
