; Generated by Isabelle/LLVM-shallow
target datalayout = "e-m:e-p:64:64:64-a:0:64-n8:16:32:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f16:16:16-f32:32:32-f64:64:64-f128:128:128"
target triple = "x86_64-pc-linux-gnu"



declare float @llvm.sqrt.f32(float)

attributes #0 = { strictfp }

define float @test_float(float %a, float %b) #0 {

  start:
    %aa = fmul float %a, %a
    %bb = fmul float %b, %b
    %t_1 = fadd float %aa, %bb
    %t_11 = call float @llvm.sqrt.f32 (float %t_1)
    %t_2 = fdiv float %a, %b
    %t_12 = fsub float %t_11, %t_2
    %t_21 = fadd float %a, %b
    %t_13 = frem float %t_12, %t_21
    %x = fadd float %t_13, 0x3FE0000000000000
    ret float %x
}
